version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: scripts/install-docker.sh
      timeout: 300
      runas: root
  AfterInstall:     
    - location: scripts/run-container.sh
      timeout: 300
      runas: root
